#!/usr/bin/env python3
"""scripts/set-creds-web.py

A tiny localhost web server that serves a form to fill in the
TELEGRAM_BOT_TOKEN / ALLOWED_USER_IDS / LLM_API_KEY for the phone's
grandpa-bob .env. On submit it writes the .env to /tmp and pushes
it to /sdcard/Download/grandpa-bob-deploy/.env.secrets on the
phone, so you can `cp` it into ~/grandpa-bob/.env in Termux.

Listens on 127.0.0.1:8181 (localhost only — not reachable from the
network). Open the URL in your browser.

Usage:
    python3 scripts/set-creds-web.py
"""
import subprocess
import sys
from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import parse_qs

STAGE_DIR = "/sdcard/Download/grandpa-bob-deploy"
SECRETS_FILE = "/tmp/grandma-secrets.env"
PORT = 8181

HTML = """<!DOCTYPE html>
<html><head>
<title>grandpa-bob credentials</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 640px; margin: 40px auto; padding: 0 20px; }
  h2 { color: #333; }
  label { display: block; margin: 16px 0 4px; font-weight: 600; }
  input[type=text], input[type=password] { width: 100%; padding: 8px; font-family: monospace;
                                          font-size: 14px; box-sizing: border-box; }
  input[type=submit] { margin-top: 24px; padding: 10px 20px; background: #2563eb; color: white;
                       border: none; border-radius: 4px; cursor: pointer; font-size: 16px; }
  input[type=submit]:hover { background: #1d4ed8; }
  .ok { background: #d1fae5; border: 1px solid #6ee7b7; padding: 16px; border-radius: 4px; }
  pre { background: #1f2937; color: #f9fafb; padding: 12px; border-radius: 4px; overflow-x: auto; }
  small { color: #666; }
</style>
</head><body>
<h2>grandpa-bob phone credentials</h2>
<form method="POST">
  <label for="telegram_token">Telegram bot token</label>
  <input type="text" id="telegram_token" name="telegram_token" placeholder="123456:ABC-DEF...">
  <small>Get one from <code>@BotFather</code> in Telegram (send <code>/newbot</code>).</small>

  <label for="user_id" style="margin-top:16px">Your Telegram user ID</label>
  <input type="text" id="user_id" name="user_id" placeholder="123456789">
  <small>Message <code>@userinfobot</code> to find yours.</small>

  <label for="hf_key" style="margin-top:16px">Hugging Face API key</label>
  <input type="password" id="hf_key" name="hf_key" placeholder="hf_...">
  <small>From <a href="https://huggingface.co/settings/tokens">huggingface.co/settings/tokens</a> (needs &quot;Inference Providers&quot; permission).</small>

  <input type="submit" value="Save to phone">
</form>
</body></html>
"""

OK_HTML = """<!DOCTYPE html>
<html><head><title>saved</title>
<style>body{font-family:system-ui,sans-serif;max-width:640px;margin:40px auto;padding:0 20px;}
pre{background:#1f2937;color:#f9fafb;padding:12px;border-radius:4px;overflow-x:auto;}
.ok{background:#d1fae5;border:1px solid #6ee7b7;padding:16px;border-radius:4px;}</style>
</head><body>
<div class="ok"><b>Saved!</b> Credentials written to <code>__STAGE__/.env.secrets</code> on the phone.</div>
<p>Now open Termux on the phone and run:</p>
<pre>cp __STAGE__/.env.secrets ~/grandpa-bob/.env \
  &amp;&amp; tmux kill-session -t bot \
  &amp;&amp; tmux new -d -s bot 'cd ~/grandpa-bob &amp;&amp; npm run dev 2&gt;&amp;1 | tee ~/bot.log'</pre>
<p>After verifying the bot works, you can remove the staging file:</p>
<pre>rm __STAGE__/.env.secrets</pre>
</body></html>
"""

class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        self._send(200, "text/html", HTML)

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(length).decode()
        params = parse_qs(body)
        token = params.get("telegram_token", [""])[0].strip()
        user_id = params.get("user_id", [""])[0].strip()
        hf_key = params.get("hf_key", [""])[0].strip()
        if not (token and user_id and hf_key):
            self._send(400, "text/html", "<h2>missing one or more fields</h2>")
            return
        env = (
            f"# generated by scripts/set-creds-web.py\n"
            f"TELEGRAM_BOT_TOKEN={token}\n"
            f"ALLOWED_USER_IDS={user_id}\n"
            f"\n"
            f"LLM_BASE_URL=https://router.huggingface.co/v1\n"
            f"LLM_API_KEY={hf_key}\n"
            f"LLM_MODEL=google/gemma-4-26B-A4B-it:novita\n"
            f"\n"
            f"STT_BACKEND=sherpa\n"
            f"SHERPA_URL=http://127.0.0.1:8178\n"
            f"STT_LANGUAGE=en\n"
            f"\n"
            f"WORKSPACE_DIR=/data/data/com.termux/files/home/grandma-workspace\n"
        )
        with open(SECRETS_FILE, "w") as f:
            f.write(env)
        try:
            subprocess.run(
                ["adb", "push", SECRETS_FILE, f"{STAGE_DIR}/.env.secrets"],
                check=True, capture_output=True,
            )
        except subprocess.CalledProcessError as e:
            self._send(500, "text/html", f"<h2>adb push failed</h2><pre>{e.stderr.decode()}</pre>")
            return
        self._send(200, "text/html", OK_HTML.replace("__STAGE__", STAGE_DIR))

    def _send(self, code, ctype, body):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.end_headers()
        self.wfile.write(body.encode())

    def log_message(self, format, *args):
        sys.stderr.write("%s - %s\n" % (self.address_string(), format % args))

if __name__ == "__main__":
    print(f"\ngrandpa-bob credentials form: http://127.0.0.1:{PORT}\n")
    HTTPServer(("127.0.0.1", PORT), Handler).serve_forever()
